<!DOCTYPE html>
<html>
<head>
  <title>Function Reference</title>
  <meta name="keywords" content="{DIRS}">
  <meta name="description" content="{DIRS}">
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <meta name="generator" content="m2html &copy; 2005 Guillaume Flandin">
  <meta name="robots" content="index, follow">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link type="text/css" rel="stylesheet" href="{MASTERPATH}docs.css">
</head>
<body>
<a name="_top"></a>
<div class="wrapper">
	<nav id="sidebar">
		<div class="sidebar-header">
			<h3>Directories</h3>
        </div>
        <ul class="list-unstyled components">
			<li class="">
				<a href="#">Home</a>
            </li>
			<!-- BEGIN rowdir --> 		
			<li>
				<a href="#{DIR_NAME}" data-toggle="collapse" aria-expanded="false">{DIR_NAME}</a>
                <ul class="collapse list-unstyled" id="{DIR_NAME}">
				<!-- BEGIN row-m -->
					<li><a href="{FILE_SOURCE}" title="{H1LINE}">{NAME} <!-- BEGIN mexfile --> <img src="{MASTERPATH}mex.png" alt="MEX" border="0"> <!-- END mexfile --> </a></li>
				<!-- END row-m -->	
                </ul>
            </li>
			<!-- END rowdir -->
        </ul>
    </nav>

	<div id="content">
        <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn">
			<i class="glyphicon glyphicon-align-left"></i>
            <span>Menu</span>
        </button>
		<h1 id="title">OPC: Optimal Projections for Clustering</h1>
		<h3 id="subtitle"> <center>An open source MATLAB and Octave library for Dimensionality Reduction for Clustering</center></h3>
		<hr><p><font color="black">
		OPC is an open source MATLAB and GNU Octave package that implements clustering methods that seek the optimal low dimensional subspace to identify clusters.<br />
		Whenever the data contains irrelevant features, or correlations
		among subsets of features exist (which is typical in
		high-dimensional data), or when clusters are defined in
		different subspaces, the spatial data structure becomes less
		informative about the underlying clusters. Under these
		conditions clustering algorithms need to simultaneously solve
		two interrelated problems: (i) identify the subspace in which
		clusters can be distinguished, and (ii) associate observations
		to clusters. <br />
		OPC focuses on methods which seek low dimensional subspaces
		that are optimal with respect to specific clustering criteria.
		This distinguishes the methods in OPC from generic
		dimensionality reduction techniques that optimise objective
		functions that are not related to any clustering criterion, and
		are therefore not guaranteed to preserve the cluster structure.
		</font></p>
		<hr><address>Generated by <strong><a href="http://www.artefact.tk/software/matlab/m2html/" target="_parent">m2html</a></strong> &copy; 2005</address>
    <div>

</div>

<!-- BEGIN idrow -->
<!-- BEGIN idcolumn -->
<!-- -->
<!-- END idcolumn -->
<!-- END idrow -->


<!-- BEGIN search -->
<h2>Search Engine</h2>
<form class="search" action="{PHPFILE}" target="function" method="get">
<input class="search" type="text" name="query" value="" size="20" accesskey="s"/>&nbsp;
<input type="submit" name="submit" value="OK">
</form>
<!-- END search -->

<!-- BEGIN graph -->
<h2>Dependency Graph</h2>
<ul style="list-style-image:url({MASTERPATH}simulinkicon.gif)">
<li>View the <a href="{LGRAPH}" target="function">Graph</a>.</li>
</ul>
<!-- END graph -->

<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
$(document).ready(function () {
    $('#sidebarCollapse').on('click', function () {
        $('#sidebar, #content').toggleClass('active');
        $('.collapse.in').toggleClass('in');
        $('a[aria-expanded=true]').attr('aria-expanded', 'false');
    });
});
</script>
</body>
</html>
